export enum ErrorCode {
  // Booking
  SEAT_NOT_FOUND = 'SEAT_NOT_FOUND',
  SEAT_NOT_AVAILABLE = 'SEAT_NOT_AVAILABLE',
  SEAT_UPDATED_BY_OTHER_TRANSACTION = 'SEAT_UPDATED_BY_OTHER_TRANSACTION',
  SEAT_BEING_BOOKED_BY_OTHER_REQUEST = 'SEAT_BEING_BOOKED_BY_OTHER_REQUEST',
}
