version: '3.8'
services:
  redis:
    image: redis:latest
    ports:
      - '6380:6379'
  postgres:
    image: postgres:15
    container_name: airlines
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: airlines
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
